services:
  rabbitmq:
    image: rabbitmq:4.0-management-alpine
    restart: unless-stopped
    container_name: rabbitmq
    ports:
      - "6458:15672"
      - "6457:5672"
    healthcheck:
      test: [ "CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5    
    volumes:
      - ./data/rabbitmq/data/:/var/lib/rabbitmq/
      - ./data/rabbitmq/logs/:/var/log/rabbitmq/
      - ./data/rabbitmq/logs:/var/tmp/rabbitmq-tracing
      - ./scripts/rabbit_definitions.json:/opt/definitions.json:ro
      - ./scripts/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro   
    


