version: '3.8'

services:
  soap:
    image: alanfg120/soap:latest
    container_name: soap
    ports:
      - "6456:8080"
    restart: always
    environment:
      MYSQL_URL : ${MYSQL_URL}
      MYSQL_USERNAME : ${MYSQL_USERNAME}
      MYSQL_PASSWORD : ${MYSQL_USERNAME}
    networks:
      - mysql_default
networks:
  mysql_default:
    external: true



  