version: '3.8'

services:
  soap:
    image: alanfg120/soap:latest
    container_name: soap
    ports:
      - "3001:8080"
    restart: always
    networks:
      - soap_default
networks:
   soap_default:


  