version: '3'
services:
  master:
    env_file:
      - server.env
    image: mysql/mysql-server:8.0.12
    ports:
      - "3301:3306"
    command: ["mysqld","--server_id=1","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    volumes:
      - master-data:/var/lib/mysql
  node-1:
    env_file:
      - server.env
    image: mysql/mysql-server:8.0.12
    command: ["mysqld","--server_id=2","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3302:3306"
    volumes:
      - node1-data:/var/lib/mysql
  node-2:
    env_file:
      - server.env
    image: mysql/mysql-server:8.0.12
    command: ["mysqld","--server_id=3","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin","--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64","--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]
    ports:
      - "3303:3306"
    volumes:
      - node2-data:/var/lib/mysql
  shell:
    env_file:
      - shell.env
    image: neumayer/mysql-shell-batch
    volumes:
        - ./scripts/:/scripts/
    depends_on:
      - master
      - node-1
      - node-2
  router:
    env_file:
      - router.env
    image: mysql/mysql-router:8.0
    ports:
      - "6446:6446"
      - "6447:6447" 
    depends_on:
      - master
      - node-1
      - node-2
      - shell
    restart: on-failure
volumes:
  master-data:
  node1-data:
  node2-data:
  
