services:
  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z-cpuv1
    container_name: minio
    ports:
      - "6448:9000"
      - "6449:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_USE_SSL: "false"
      #MINIO_ENDPOINT: host.docker.internal:9000
    restart: unless-stopped
    volumes:
      - ./data/minio_data:/data
    command: server /data --console-address ":9001"  
  mc:
    image: minio/mc:RELEASE.2024-11-17T19-35-25Z-cpuv1
    container_name: minio_mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        until mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD}; do
          echo 'Waiting for MinIO to be ready...';
          sleep 3;
        done;
        mc admin user add myminio ${MINIO_READWRITE_USER} ${MINIO_READWRITE_PASS} &&
        mc admin policy attach myminio readwrite --user ${MINIO_READWRITE_USER};

        # Verificar si el root access key ya existe, si no, lo crea            
        mc admin accesskey list myminio | grep -q ${MINIO_ROOT_ACCESS_KEY} ||
        mc admin accesskey create myminio/ ${MINIO_ROOT_USER} --access-key ${MINIO_ROOT_ACCESS_KEY} --secret-key ${MINIO_ROOT_SECRET_KEY} --name admin_minio;
        
        # Verificar si el readwrite access key ya existe, si no, lo crea
        mc admin accesskey list myminio | grep -q ${MINIO_READWRITE_ACCESS_KEY} ||
        mc admin accesskey create myminio/ ${MINIO_READWRITE_USER} --access-key ${MINIO_READWRITE_ACCESS_KEY} --secret-key ${MINIO_READWRITE_SECRET_KEY} --name readwrite;
      "
    volumes:
      - ./data/minio_data:/data
